fix tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,37 +1,41 @@
 name: Test PRs
 
 on:
-    pull_request:
-        branches:
-            - main
+  pull_request:
+    branches:
+      - main
 
 jobs:
-    test:
-        runs-on: macos-14
+  test:
+    runs-on: macos-14
 
-        steps:
-        - name: Checkout code
-          uses: actions/checkout@v2
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-        - name: Set up Python
-          run: |
-            brew install python@3.10
-            python3 -m venv env
-            source env/bin/activate
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
 
+      - name: Install MLX
+        run: |
+          pip install mlx>=0.15
 
-        - name: Run style checks
-          run: |
-            pip install pre-commit
-            pre-commit run --all
-            if ! git diff --quiet; then echo 'Style checks failed, please install pre-commit and run pre-commit run --all and push the change'; exit 1; fi
+      - name: Install pre-commit
+        run: |
+          python -m pip install pre-commit
+          pre-commit run --all
+          if ! git diff --quiet; then
+            echo 'Style checks failed, please install pre-commit and run pre-commit run --all and push the change'
+            exit 1
+          fi
 
-        - name: Install dependencies
-          run: |
-            pip install pytest
-            pip install -e .
+      - name: Install package and dependencies
+        run: |
+          python -m pip install pytest
+          python -m pip install -e .
 
-        - name: Run Python tests
-          run: |
-            cd mlx_vlm/
-            pytest -s ./tests
+      - name: Run tests
+        run: |
+          pytest -s .
